spring:
  application:
    name: trip-service
  liquibase:
    enabled=false
  datasource:
    url: jdbc:postgresql://localhost/trip
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
